name: Publish to PowerShell Gallery

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate module manifest
        shell: pwsh
        run: |
          $psd1Path = Join-Path $PWD 'Nebula.Log.psd1'
          Test-ModuleManifest -Path $psd1Path -Verbose

      - name: Prepare module package
        shell: pwsh
        run: |
          $outDir = "$PWD\build"
          if (Test-Path $outDir) { Remove-Item -Recurse -Force $outDir }
          New-Item -ItemType Directory -Path $outDir | Out-Null
      
          $includeFiles = @('*.psd1', '*.psm1', 'README.md', 'icon.png')
          foreach ($pattern in $includeFiles) {
              Get-ChildItem -Path $PWD -Filter $pattern -File | Copy-Item -Destination $outDir -Force
          }

      - name: Publish module to PowerShell Gallery
        shell: pwsh
        run: |
          $modulePath = "$PWD\build"

          if (-not (Get-PSRepository -Name 'PSGallery' -ErrorAction SilentlyContinue)) {
              Register-PSRepository -Name 'PSGallery' -SourceLocation 'https://www.powershellgallery.com/api/v2' -InstallationPolicy Trusted
          }

          Publish-Module -Path $modulePath `
                         -NuGetApiKey "${{ secrets.NUGET_API_KEY }}" `
                         -Verbose
